### ISSUE TITLE
ex-navigation is removed in RN0.44 (Expo SDK 18)

### ISSUE THREAD

**Issue by turbozv** [BibleStudyFellowshipCN/BSFApp#15]
Our app won't work >= SDK18, we need to migrate to react-navigation

**Comment by mikewqg** [comment]
If we do nothing, our app stops working??

发自我的 Windows Phone
________________________________

**Comment by turbozv** [comment]
No worries, no impact to our existing app, which is using SDK15.

**Comment by turbozv** [comment]
Thanks to Lord, I have good news!

I tried to update ex-navigation to the latest, the issue is gone. We're
good to use SDK19 now :)

**Comment by mikewqg** [comment]
Great news indeed. Praise to our mighty God!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
